version: 2
project_name: lazyreview

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: lazyreview
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "Features"
      regexp: "^.*feat.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix.*$"
      order: 1
    - title: "Other"
      order: 999

# Homebrew tap (disabled until homebrew-tap repo is created)
# To enable:
# 1. Create https://github.com/tauantcamargo/homebrew-tap repository
# 2. Add HOMEBREW_TAP_TOKEN secret to GitHub Actions with repo write access
# brews:
#   - repository:
#       owner: tauantcamargo
#       name: homebrew-tap
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     homepage: https://github.com/tauantcamargo/lazyreview
#     description: Terminal UI for code review across multiple Git providers
#     license: MIT
#     install: |
#       bin.install "lazyreview"
#     test: |
#       system "#{bin}/lazyreview", "--version"

nfpms:
  - package_name: lazyreview
    homepage: https://github.com/tauantcamargo/lazyreview
    maintainer: Tauan Camargo <tauantcamargo@gmail.com>
    description: Terminal UI for code review across multiple Git providers
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

release:
  github:
    owner: tauantcamargo
    name: lazyreview
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

announce:
  skip: true
