import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['src/**/*.test.{ts,tsx}'],
    environmentMatchGlobs: [['src/**/*.test.tsx', 'jsdom']],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/cli.tsx',
        'src/app.tsx',
        'src/screens/**',
        'src/**/index.ts',
        'src/components/layout/TopBar.tsx',
        'src/components/layout/Sidebar.tsx',
        'src/components/layout/MainPanel.tsx',
        'src/components/layout/HelpModal.tsx',
        'src/components/common/Modal.tsx',
        'src/components/common/Divider.tsx',
        'src/components/common/BorderedBox.tsx',
        'src/components/common/LoadingIndicator.tsx',
        'src/components/common/MultiLineInput.tsx',
        'src/components/common/Spinner.tsx',
        'src/components/pr/MergeModal.tsx',
        'src/components/pr/ReviewModal.tsx',
        'src/components/pr/CommentModal.tsx',
        'src/components/common/FilterModal.tsx',
        'src/components/common/SortModal.tsx',
        'src/components/pr/PRHeader.tsx',
        'src/components/pr/PRListItem.tsx',
        'src/components/pr/PRTabs.tsx',
        'src/components/pr/CommitsTab.tsx',
        'src/components/pr/BatchReviewModal.tsx',
        'src/components/pr/CheckStatusIcon.tsx',
        'src/components/pr/CheckStatusSummary.tsx',
        'src/components/pr/DiffComment.tsx',
        'src/components/pr/TimelineItemView.tsx',
        'src/components/pr/ConversationsTab.tsx',
        'src/components/pr/DiffView.tsx',
        'src/components/pr/SideBySideDiffView.tsx',
        'src/components/pr/ReReviewModal.tsx',
        'src/components/pr/ReviewSummary.tsx',
        'src/components/pr/FilesTab.tsx',
        'src/components/pr/FileTree.tsx',
        'src/components/settings/SettingRow.tsx',
        'src/components/layout/TokenInputModal.tsx',
        'src/hooks/useAuth.ts',
        'src/hooks/useConfig.ts',
        'src/hooks/useGitHub.ts',
        'src/hooks/useActivePanel.ts',
        'src/hooks/useCommentActions.ts',
        'src/hooks/useInputFocus.tsx',
        'src/hooks/useManualRefresh.ts',
        'src/hooks/usePRDetailModals.ts',
        'src/hooks/usePRStateActions.ts',
        'src/hooks/usePagination.ts',
        'src/hooks/usePendingReview.ts',
        'src/hooks/useReviewActions.ts',
        'src/services/GitHubApiLive.ts',
        'src/theme/types.ts',
        'src/models/inline-comment.ts',
      ],
      thresholds: {
        lines: 58,
        statements: 58,
        functions: 60,
        branches: 88,
      },
    },
  },
  resolve: {
    alias: {
      '@': '/src',
    },
  },
})
