name: Bug Report
description: Report a bug or unexpected behavior in LazyReview
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'lazyreview'
        2. Navigate to '...'
        3. Press '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment.
      placeholder: |
        - LazyReview version: (run `lazyreview --version` or `npm list -g lazyreview`)
        - Node.js version: (run `node --version`)
        - Operating System: (e.g., macOS 14.2, Ubuntu 22.04, Windows 11)
        - Terminal: (e.g., iTerm2, Alacritty, Windows Terminal)
      value: |
        - LazyReview version: 
        - Node.js version: 
        - Operating System: 
        - Terminal: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: If applicable, add error messages, logs, or screenshots.
      placeholder: Paste logs or drag and drop screenshots here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might help...
    validations:
      required: false
