name: Question or Discussion
description: Ask a question or start a discussion about LazyReview
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Have a question about LazyReview? Ask away!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question.
      placeholder: |
        I'm trying to...
        I've looked at...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information or screenshots that might help.
      placeholder: Any additional details...
    validations:
      required: false
